export enum ErrorCode {
  // Provider
  PROVIDER_AUTH_FAILED = 'PROVIDER_AUTH_FAILED',
  PROVIDER_TIMEOUT = 'PROVIDER_TIMEOUT',
  PROVIDER_UNAVAILABLE = 'PROVIDER_UNAVAILABLE',
  PROVIDER_RATE_LIMITED = 'PROVIDER_RATE_LIMITED',
  PROVIDER_CIRCUIT_OPEN = 'PROVIDER_CIRCUIT_OPEN',
  PROVIDER_UNKNOWN_ERROR = 'PROVIDER_UNKNOWN_ERROR',

  // Consultation
  ALL_PROVIDERS_FAILED = 'ALL_PROVIDERS_FAILED',
  CNJ_INVALID = 'CNJ_INVALID',
  CNJ_NOT_FOUND = 'CNJ_NOT_FOUND',
  POLL_TIMEOUT = 'POLL_TIMEOUT',

  // Webhook
  WEBHOOK_INVALID_SIGNATURE = 'WEBHOOK_INVALID_SIGNATURE',
  WEBHOOK_PARSE_FAILED = 'WEBHOOK_PARSE_FAILED',

  // General
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
}
